
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/user/Header";
import Footer from "@/components/user/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { getMe } from "@/api/server-api.js";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Ishop",
  description: "Generated by Ranjeet gurjar",
};

export default async  function UserLayout({
  children,
}) {
   const user = await getMe();
  
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col antialiased`}
    >
      <ReduxProvider>
        <Header user={user}/>

        <main className="flex-1">
          {children}
        </main>

        <Footer />
      </ReduxProvider>
    </div>
  );
}